### ISSUE TITLE
noice 导致 neovide 奔溃

### ISSUE THREAD

**Issue by leisurelicht** [leisurelicht/LichtVim#6]
在 neovide 中使用 noice 插件会导致在某些情况下（比如输入 `dt` 时），neovide 会直接完全退出

Issue： https://github.com/folke/noice.nvim/issues/17

**Comment by hf-xz** [comment]
我进命令模式就崩QAQ

**Comment by leisurelicht** [comment]
> 我进命令模式就崩QAQ

目前只能选择不在neovide中使用noice了，我看到现在好像连原因都不是很确定
